name: anan-vue Dockerfile CI
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          echo MODULE_VERSION=$(echo ${GITHUB_REF:10}) >> $GITHUB_ENV
          echo DOCKER_MIRROR_SERVER=registry.cn-hongkong.aliyuncs.com >> $GITHUB_ENV
          echo DOCKER_MIRROR_NS=fosin >> $GITHUB_ENV

      - name: Checkout branche
        uses: actions/checkout@v2
        with:
          # The branch, tag or SHA to checkout. When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, defaults to `master`.
          ref: ${{ env.MODULE_VERSION }}

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'

      - name: Install Dependencies
        run: |
          npm install @vue/cli@4.5.17
          npm install

      - name: Build with Node
        run: |
          npm run build:prod

      - name: Docker build and push image Nginx
        env:
          MODULE_NAME: anan-vue
        run: |
          docker login --username=${{ secrets.alidocker_username }} --password=${{ secrets.alidocker_secrect }} ${{ env.DOCKER_MIRROR_SERVER }}
          docker build . -t ${{ env.DOCKER_MIRROR_SERVER }}/${{ env.DOCKER_MIRROR_NS }}/$MODULE_NAME:$MODULE_VERSION -f deploy/Dockerfile
          docker push ${{ env.DOCKER_MIRROR_SERVER }}/${{ env.DOCKER_MIRROR_NS }}/$MODULE_NAME:$MODULE_VERSION

      - name: Docker build and push image Ingress Nginx Controller
        env:
          MODULE_NAME: ingress-nginx-controller
        run: |
          docker build . -t ${{ env.DOCKER_MIRROR_SERVER }}/${{ env.DOCKER_MIRROR_NS }}/$MODULE_NAME:$MODULE_VERSION -f deploy/ingress-nginx-controller.Dockerfile
          docker push ${{ env.DOCKER_MIRROR_SERVER }}/${{ env.DOCKER_MIRROR_NS }}/$MODULE_NAME:$MODULE_VERSION

      - name: Docker build and push image Nginx Ingress Controller
        env:
          MODULE_NAME: nginx-ingress-controller
        run: |
          docker build . -t ${{ env.DOCKER_MIRROR_SERVER }}/${{ env.DOCKER_MIRROR_NS }}/$MODULE_NAME:$MODULE_VERSION -f deploy/nginx-ingress-controller.Dockerfile
          docker push ${{ env.DOCKER_MIRROR_SERVER }}/${{ env.DOCKER_MIRROR_NS }}/$MODULE_NAME:$MODULE_VERSION
          docker logout
